### ISSUE TITLE
Add random secret (in vault) for presto cluster communication

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/terraform-nomad-presto#29]
A random secret is required for cluster communication in presto.
This secret should be added to vault and used by presto by referencing vault in a template stanza.

**Comment by zhenik** [comment]
it could be done via ansible tasks

**Comment by Neha-Sinha2305** [comment]
So we mean to replace this hardcoded cluster secret?
https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/f7dedcb09f20d151b15cf0bf779d88794d3e523d/example/main.tf#L6

**Comment by Neha-Sinha2305** [comment]
Inorder to use vault stanza in nomad jobs to retrieve secrets need to have vault integration with nomad in place as sited by Ole Andre in the following issue :[Nomad needs to be vault integrated in order to use vault interpolations in jobs]( https://github.com/fredrikhgrelland/vagrant-hashistack/issues/380
).
Without this integration in place, i end up getting the following error: 
```
stderr: 
Error: error applying jobspec: Unexpected response code: 500 (Vault not enabled and Vault policies requested)

  on ../main.tf line 57, in resource "nomad_job" "nomad_job_presto":
  57: resource "nomad_job" "nomad_job_presto" {
```
### Workaround :
Trying out :https://github.com/fredrikhgrelland/vagrant-hashistack/issues/380#issuecomment-704769756
